name: Psalm Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macOS-latest ]
        php-versions: [ '7.2', '7.3', '7.4', '8.0' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true
          report_file: results.sarif
          composer_require_dev: true
          composer_ignore_platform_reqs: true

#      - name: Upload Security Analysis results to GitHub
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: results.sarif
